export const AuthConstants = {
    REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

    SIGNIN_SUCCESS: 'USER_SIGNIN_SUCCESS',
    SIGNIN_FAILURE: 'USER_SIGNIN_FAILURE',

    SIGN_OUT: 'USER_SIGNOUT', 
}