export const AuthConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    SIGNIN_SUCCESS: 'USERS_SIGNIN_SUCCESS',
    SIGNIN_FAILURE: 'USERS_SIGNIN_FAILURE',

    SIGN_OUT: 'USERS_SIGNOUT', 
}